version: '3.9'
services:
  db:
    image: mysql:8.0.29-debian
    restart: always
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_ROOT_PASSWORD: "${DB_PASS}"
    expose:
      - "${DB_PORT}"
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - db:/var/lib/mysql
  api:
    build:
      dockerfile: docker/go/Dockerfile
    environment:
      DB_HOST: db
      DB_NAME: "${DB_NAME}"
      DB_PASS: "${DB_PASS}"
      DB_PORT: "${DB_PORT}"
      DB_USER: "${DB_USER}"
      MONGODB_URI: "${MONGODB_URI}"
      MONGODB_DB: "${MONGODB_DB}"
      MONGODB_COLLECTION: "${MONGODB_COLLECTION}"
      APP_PORT: "${APP_PORT}"
      VENDOR_QONTAK: "${VENDOR_QONTAK}"
      MESSAGE_TEMPLATE: "${MESSAGE_TEMPLATE}"
      CHANNEL_ID: "${CHANNEL_ID}"
      TOKEN_QONTAK: "${TOKEN_QONTAK}"
      JWT_SECRET: "${JWT_SECRET}"
      TOTAL_DEVICE: "${TOTAL_DEVICE}"
      NUMBER_FAKE: "${NUMBER_FAKE}"
      OTP_FAKE: "${OTP_FAKE}"
    ports:
      - "${APP_PORT}:${APP_PORT}"
    links:
      - db
networks:
  default:
    name: employee-service-default
volumes:
  db:
    external: false
