apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: qgrowid-development
  name: qgrowid-user-dpl
  labels:
    app: qgrowid-user-dpl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qgrowid-user-dpl
  template:
    metadata:
      namespace: qgrowid-development
      labels:
        app: qgrowid-user-dpl
    spec:
      imagePullSecrets:
        - name: qgrowid-registry
      containers:
        - name: qgrowid-user-dpl
          image: registry.gitlab.com/qgrow.id1/qgames-user-service/dev-k8s:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3001